<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDJOCuxN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDJOCuxN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDJOCuxN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDJOCuxN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDJOCuxN\App_KernelDevDebugContainer([
    'container.build_hash' => 'DJOCuxN',
    'container.build_id' => '5adac42e',
    'container.build_time' => 1656940197,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDJOCuxN');
