<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4rMJHmP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4rMJHmP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4rMJHmP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4rMJHmP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4rMJHmP\App_KernelDevDebugContainer([
    'container.build_hash' => '4rMJHmP',
    'container.build_id' => 'b27a892d',
    'container.build_time' => 1656944871,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4rMJHmP');
